lib/volume.js
lib/volume.test.js
src/volume.test.ts
src/volume.ts

Fix existsSync when file not found

---

README.md
lib/volume.js
lib/volume.test.js
src/volume.test.ts
src/volume.ts

Closes #29
I’m not resetting `Volume.ino` because it may affect other volumes — let me know if I’m wrong.

Add vol.reset() method

---

src/__tests__/volume.test.ts
src/volume.ts

Fixes https://github.com/streamich/memfs/issues/58

fix: fs.open on directory as read-only

---

src/__tests__/volume.test.ts
src/volume.ts

I break it a bit in #174 :cry:

Attempt to read a non-existing file should throw ENOENT

---

src/__tests__/node.test.ts
src/__tests__/volume.test.ts
src/index.ts
src/node.ts
src/promises.ts
src/volume.ts

Also removed some unused imports.

Export directory json from index

---

renovate.json

This should make things slightly nicer.

chore: update `renovate.json` to group jest monorepo

---

src/__tests__/volume.test.ts
src/volume.ts

fix: throw EEXIST when opening file with 'wx' that already exists

---

src/__tests__/process.test.ts
src/node.ts
src/process.ts

fix: dont patch `getuid` and `getgid` on process anymore #809

---

.github/workflows/checks.yml
package.json

Relates to #868 and https://github.com/streamich/unionfs/pull/740 - releases won't actually succeed until @streamich sets up the release token secret.

ci: setup GHA checks

---

.github/workflows/lint.yml
package.json

I forgot to include this in #871

ci: setup `commitlint` workflow

---

yarn.lock

Renovate seems to not be working correctly so have done a manual refresh of the lockfile which should close a bunch of bot-managed PRs

chore: manually refresh lockfile

---

src/__tests__/process.test.ts
src/__tests__/volume.test.ts
src/volume.ts

- See https://github.com/streamich/memfs/issues/558
The fix for this is similar to the others I just submitting, so here it is.
Resolves #558

fix: support calling `chmod` on a directory

---

src/__tests__/volume/realpathSync.test.ts
src/volume.ts

-  https://github.com/streamich/memfs/issues/863
Resolves #863

fix: return `/` when calling `realpathSync` with `/`

---

src/fsa/types.ts

BREAKING CHANGE: 🧨 no breaking changes in this commit, but bumping to get this to v4 in NPM

Bump to v4 and FSA types

---

src/Dirent.ts
src/__tests__/volume/readdirSync.test.ts
src/node/types/options.ts
src/volume.ts

refactor: apply `prettier`

---

src/volume.ts

chore: remove unused array

---

src/__tests__/volume/readdirSync.test.ts

test: ensure consistent order

---

src/json-joy/json-pack/cbor/CborDecoder.ts
src/json-joy/json-pointer/index.ts
src/json-joy/json-pointer/types.ts

Technically makes things a bit smaller but more importantly fixes the release

feat: inline `json-pointer` types

---

src/json-joy/json-pack/cbor/CborDecoder.ts
src/json-joy/json-pointer/index.ts
src/json-joy/json-pointer/types.ts

This reverts commit 9b009b792553756bc51210ff65dc2ff6da7ef8df.

feat: actually don't inline `json-pointer` types

---

package.json
src/print/index.ts
yarn.lock

Follow up to [this comment](https://github.com/streamich/memfs/pull/1028#issuecomment-2088052444)

fix: replace `sonic-forest` with `tree-dump`

---

package.json
src/__tests__/volume/FileHandle.test.ts
src/fsa-to-node/json.ts
src/node/FileHandle.ts
src/node/types/FsPromisesApi.ts
src/node/types/misc.ts
src/node/types/options.ts
yarn.lock

Partially addresses https://github.com/streamich/memfs/issues/1044

Add initial `.readableWebStream()` implementation

---

src/__tests__/volume/mkdirSync.test.ts
src/volume.ts

Looks like these slipped in in #1059

fix: remove `debugger` statement

---

src/Stats.ts
src/__tests__/volume/statSync.test.ts
src/node.ts

This adds it to stat too, so rdev will propagate.

feat: allow setting rdev on node
