streamich/memfs

package.json, yarn.lock
I’m trying to make it work with [graceful-fs](https://github.com/isaacs/node-graceful-fs). This fixes one of the two issues I have: it tries to access `fdatasync` which was added in the new version of fs-monkey.
=> Upgrade fs-monkey

lib/volume.js, package.json, src/volume.ts
**NOTE** This PR requires fs-monkey to have the [PR](https://github.com/streamich/fs-monkey/pull/2)  merged and published before this will work.
Using a memfs as for `node_modules` via fs-monkey was having a problem because unixify was inline-required (and gave problems during module resolution).
I inlined unixify in fs-monkey (as part of the [fix ](https://github.com/streamich/fs-monkey/pull/2) for win32 there and then pulled thru the implementation so that there was a few less dependencies (since fs-monkey was already a dep).
=> updated fs-monkey and fixed win32 issue

lib/volume.js, src/volume.ts
This fixes an accidental recursion (when the intent was to call the original function)
=> fixes accidental recursion with resolve function

lib/node.js, lib/volume.js, src/__tests__/node.test.ts, src/__tests__/volume.test.ts, src/node.ts, src/volume.ts
The `mode` variable inside a `Node` should not only indicate the type of Node it is (directory, file, etc), but should also contain information about it's permissions.
This PR makes sure that the mode is `|=`'ed with the `perm` variable when creating a new node and when chmoding. Also adds tests.
=> Make sure mode is OR'ed with the permission on init and when chmoding

src/volume.ts
Node 8 has it, but Node 6 does not have that method.
=> fix: check if .destroy exists

src/__tests__/volume.test.ts, src/volume.ts
```
❯ node
> var fs = require('fs')
undefined
> fs.readFileSync('package.json')
<Buffer 7b 0a 20 20 22 6e 61 6d 65 22 3a 20 22 6d 72 6d 2d 63 6f 72 65 22 2c 0a 20 20 22 76 65 72 73 69 6f 6e 22 3a 20 22 30 2e 30 2e 30 2d 64 65 76 65 6c 6f ... >
> fs.readFileSync('node_modules')
Error: EISDIR: illegal operation on a directory, read
at Object.fs.readSync (fs.js:675:18)
at tryReadSync (fs.js:540:20)
at Object.fs.readFileSync (fs.js:583:19)
>
```
=> readFile should throw when reading a directory

src/setImmediate.ts
Fixes the following issue when attempted in a browser under some
circumstances where `this !== global`:
```
Uncaught TypeError: Illegal invocation
at Volume.wrapAsync (index-bundle.js:8692)
at Volume.stat (index-bundle.js:9261)
```
Tested bundled using rollup in Chrome 69
=> fix: add setImmediate.bind

docs/api-status.md, docs/reference.md, src/__tests__/volume.test.ts, src/volume.ts
Add support for `relative` option for `fs.mkdir` and `fs.mkdirSync` functions by using `vol.mkdirp` implementation. 
Make `vol.mkdirp` and `vol.mkdirpSync` functions deprecated.
=> feat: add relative option support for mkdir and mkdirSync

src/__tests__/index.test.ts, src/__tests__/volume.test.ts, src/encoding.ts, src/index.ts, src/node.ts, src/volume.ts
Add `withFileTypes` option support for `fs.readdir` and `fs.readdirSync`. 
Add new `fs.Dirent` class (obviously) which is similar to `fs.Stats` but also need the `encoding` option for constructing the name.
Move all encoding related types and functions to new `encoding.ts` file.
=> feat: support readdir withfiletypes option

README.md, docs/api-status.md, src/__tests__/index.test.ts, src/__tests__/promises.test.ts, src/__tests__/volume.test.ts, src/index.ts, src/node.ts, src/promises.ts, src/volume.ts, tsconfig.json
Fixes #147 
I saw that you assigned yourself on this issue a while ago but, since it was in may, I took the liberty of implementing it anyway. 
This pull request also ships some unreported bug fixes on which I ran into while testing the promises API. You will find the main fixes in commits de5aca656b58601d563382dbcda3789b06db6b23, be5654b5d8fb5342509033c2513b2c124dcfaadb, and a8c8998038b118cfeec1636238b391a2f4fb16d7.
This implementation warns the user that this is an experimental API, just like Node.js does. But I put the code for this in a different commit (2828f6a9227c1cf077bdd14bca5dd5b6323be2ce), so you can discard it if you don't like it.
I also separated the detection of `Promise` support in the commit 4750aeee53c685afa2194b4aaed21824d8872c19 for the same reason. Basically, if the …
=> feat: promises api

src/volume.ts
Fixes #274
It's worth to mention that, even though this change does fix the error described in #274, the code in that issue will throw a different error because of the way that tty.WriteStream works internally.
Anyway, it's good to make sure that the file descriptors follow the unix guidelines.
=> Fixed constant "fd" value to start from 0x7fffffff instead of 0xffffffff

docs/reference.md, src/__tests__/process.test.ts, src/process.ts, src/volume.ts
To suppress experimental fs.promise api warnings the SUPRESS_EXPERIMENTAL_PROMISE_WARNINGS env variable can be set to a truthy value
=> feat(volume): add env variable to suppress fs.promise api warnings

src/__tests__/process.test.ts, src/volume.ts
additional tests are added and and the default behavior is to display the fs.promise experimental warnings
=> bug(MEMFS_DONT_WARN): node fs.promises experimental warnings should be displayed by default

src/__tests__/volume/__snapshots__/mkdirSync.test.ts.snap, src/__tests__/volume/mkdirSync.test.ts, src/volume.ts
=> fix: 🐛 throw when creating root directory

package.json, src/Stats.ts, src/__tests__/hasBigInt.js, src/__tests__/volume.test.ts, src/bigint.d.ts, src/getBigInt.js, src/node.ts, src/volume.ts, tsconfig.json
This should close #275, for real this time! 
TypeScript supports `BigInt` since v3.2 but, to have access to the `BigInt` constructor, we should target `esnext` instead of `es5` which, I think, we don't actually want. As a workaround, I've added a pure JavaScript file ([`getBigInt.js`](https://github.com/streamich/memfs/blob/c640f254a72d49f4aa8cd00018f052ae5f682eba/src/getBigInt.js)) to check for the existence of `BigInt` constructor and return it if it exists or, otherwise, throw an exception. The thing is: I'm not an expert with TypeScript (I'm more used to flow actually). So maybe there's a better way of doing this with TypeScript, but I did not find it.
=> fix: 🐛 BigInt type handling

src/volume.ts
I created the `DirectoryJSON` alias just to make things easier.
I looked at enabled `strictNullChecks`, but this package just wasn't designed for it :joy:
Ideally, it'd be good to have it on at some point, or otherwise ensure all methods that can return `null` or `undefined` as thusly typed.
I've not linked the issue with this PR, as the issue could be used to track the above, and this is the change that I need ASAP to continue work on my current project.
Once I have some time, I'll be happy to look into making this library more `strictNullChecks` compatible.
=> fix: 🐛 accept `null` as value in `fromJSON` functions

src/process.ts
Fixes this issue when running in the browser:
```
process.js:5 Uncaught ReferenceError: process is not defined
at createProcess (process.js:5)
at Object../node_modules/memfs/lib/process.js (process.js:32)
at __webpack_require__ (bootstrap:19)
at Object.<anonymous> (node.js:16)
at Object../node_modules/memfs/lib/node.js (node.js:405)
at __webpack_require__ (bootstrap:19)
at Object../node_modules/memfs/lib/volume.js (volume.js:17)
at __webpack_require__ (bootstrap:19)
at Object../node_modules/memfs/lib/index.js (index.js:16)
at __webpack_require__ (bootstrap:19)
```
=> fix: check for process

src/encoding.ts, src/internal/buffer.ts, src/node.ts, src/promises.ts, src/volume.ts
This change adds a loose ponyfill for `Buffer.from` and `Buffer.allocUnsafe`, written for the usage in this package. This extends the compatibility of this project from Node v5.10 to Node v0.11.
The motivation to make such a change is to support legacy systems — often hosting platforms reliant on Node v0.12 — without unnecessarily inflating or complicating the source code, or reducing its performance.
This change addresses your request in #421 that the ponyfill be embedded rather than imported as a dependency. Credit for identifying the compatibility issue goes to @rangoo94 — thank you so much!
- Resolves #421
- Resolves #419
---
**About the strategy of this ponyfill**:
The strategy used by this ponyfill follows a convention that I observed in this project to prefer use of the spread …
=> Polyfill Buffer for Node v0.11+

src/__tests__/volume.test.ts, src/volume.ts
This allows files path to be specified in `Volume.toJSON`. Without this patch, files specificed would show up in the resulting `JSON`, but with its contets set to `null`.
Test is included.
=> feat: allow exporting file paths in Volume.toJSON

src/volume.ts
Hey there,
In node's `fs`, when doing `fs.watch` on a folder, the listener is triggered when files are added or deleted from that folder. This PR mirrors this behaviour for memfs as well.
I did not add tests because I could not find any tests for `watch`. I'd be happy to write some, but feel this might be out of scope for this PR? Let me know what you think.
Thanks!
=> fix(watch): trigger change event on a folder when children are added/deleted

src/__tests__/volume.test.ts, src/volume.ts
Hey there,
So another PR for today :)
This one adds the `recursive` capabilities of `rmdir` and `rmdirSync` https://nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback
This one does include tests, but only for rmdirSync (as I could not find base tests for `rmdir`). As in the previous PR, I'd be happy to add them in a separate PR if desired.
Thanks again!
=> fix(rmdir): support recursive option

src/volume.ts
Hello again :)
So, before this patch - if we were watching more than 11 files in the same folder, we'd get warnings like these:
```
(node:13033) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 child:delete listeners added to [Link]. Use emitter.setMaxListeners() to increase limit
```
This was because the `FSWatcher` would listen to the parent delete event to know when to emit a `rename` event for this node. Since in this case this is clearly not a memory leak, I think it makes sense to just increase the limit by 1 before adding the watcher. Let me know if you think differently and I'll try to find a different solution.
As mentioned in https://github.com/streamich/memfs/pull/485, I'd be happy to write some tests for `watch` that will include testing this …
=> fix(watch): suppress event-emitter warnings

src/volume.ts
Fixes #494.
Credit goes to @torch2424 and @syrusakbary for detecting this issue
(https://github.com/torch2424/memfs/commit/aed9a61c9f88f38f741f8275f743eb2c38298edb).
=> fix: 🐛 handle opening directories with O_DIRECTORY

package.json, src/volume.ts, tsconfig.json, yarn.lock
Because I like looking at really tiny numbers that don't matter in the real world, I did a micro benchmark of `fast-extend` vs `Object.assign` & spread:
```
extend 0.0065383616383615385
assign 0.003307592407592418
spread 0.003464735264735254
```
`Object.assign` consistently performs hits 0.003 while extend only ever gets as good as 0.004 every so often - it's most consistently at 0.005 if not higher.
However, `Object.assign` is Node 4 & above, and while `travis` tests against 8+, the engines field isn't in the `package.json`.
Hence, I've set the engine field in this PR: I think it's fine to not make this a major release, since 8 itself is EOL, and previous conversations have mentioned that we're only wanting to support the latest version of FS as it's otherwise too much overhead.
This …
=> Use object assign instead of fast extend

src/__tests__/volume/__snapshots__/mkdirSync.test.ts.snap, src/volume.ts
The `EISDIR` implementation is considered a bug in BSD operating
systems.
See the bug report at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=59739
and the POSIX specification at https://pubs.opengroup.org/onlinepubs/9699919799/functions/mkdir.html
=> fix: should throw `EEXIST` instead of `EISDIR` on `mkdirSync('/')`

src/__tests__/volume.test.ts, src/volume.ts
This adds support for nested object (literals) to `fromJSON()`. It reads much nicer and makes tests look cleaner (at least that is my personal opinion). One of the features I miss most not being able to use `mock-fs`.
I added this functionality to `fromJSON()` itself, one could argue having an additional method like `fromNestedJSON()` might be better regarding to backward compatibility. I don't think this is a problem at all, but the rather exotic corner case of calling `fromJSON()` with something like `{'dir1': {'dir2'}}` just created `dir1` so far, but would also create `dir2` from now on...
Feedback on this is highly appreciated!
Additionally this fixes a bug (at least I think it's one): so far `fromJSON()` only took the `cwd` parameter into account when creating files, not when …
=> feat: add support for nested objects to `fromJSON()`

package.json
This is required by our ifra tooling to validate the license and allows us to consumed this package.
Fixes #658
=> fix: add `The Unlicense` license SDPX in package.json

src/internal/errors.ts, src/setImmediate.ts, src/setTimeoutUnref.ts, src/volume.ts
This fixes for example `Uncaught TypeError: 'setTimeout' called on an object that does not implement interface Window.` on Firefox.
=> fix: global and timers this arg in browser

src/__tests__/volume/callback-error.test.ts, src/volume.ts
=> fix: prevent callback from triggering twice when callback throws

src/__tests__/promises.test.ts, src/__tests__/volume.test.ts, src/promises.ts, src/volume.ts
=> Support `throwIfNoEntry` in StatOptions

src/__tests__/volume/renameSync.test.ts, src/node.ts, src/volume.ts
fixes https://github.com/streamich/memfs/issues/397
I'm not familiar with the repo, just diving into it just now so forgive me if this approach is not what you guys had in mind. I didn't really see a trivial way around it other than creating a setter and recursively syncing children to parent.
When "steps" prop is set to a new value (e.g. in `renameBase`), it also goes through our children and sets their steps to synchronize with their parent which has changed.
=> fix: recursively sync children steps to fix rename

.circleci/config.yml, src/volume.ts
Fixes https://github.com/streamich/memfs/issues/828
I'm not an expert on Node internals but from briefly reading the source code, it seems the problem is that `.closed` doesn't have a setter since Node 18 (https://github.com/nodejs/node/blob/v18.0.0/lib/internal/streams/readable.js#L1243). 
The fix is to check whether `this._readableState.closed` / `this._writableState.closed` exists and use it instead of `this.closed`. This mimics other setters from the `Readable`/`Writable` class.
I also upgraded the node image in CI - to use Node 18.
The test plan is I guess just to see if CI checks pass. I saw https://github.com/streamich/memfs/pull/829 and it seems the tests failed there. From my understanding, if my fix is correct, CI checks should pass now. I also ran `yarn test` locally on Node …
=> Fix "Cannot set property closed of" on Node 18

package.json, yarn.lock
`cpy-cli` was upgraded to a new major version by #818 which has since resulted in `getBigInt.js` being copied into `lib/src/getBigInt.js` instead of `lib/getBigInt.js` which has broken the latest release (#837).
I can't see what the breaking change in `cpy-cli` that is causing this, but frankly we've only got `getBigInt.js` to support lower versions of node so we shouldn't be expecting to copy any other js file & so I've just replaced it with `cp` which is available on standard Linux & MacOS systems (and I believe PowerShell on Windows).
This'll unbreak the library for the meantime at least - we can always add `cpy-cli` back in future.
Resolves #837
=> fix: ensure js file is copied to expected place

src/volume.ts
From the Volume write function declaration, we can see the second argument has a type of Buffer or Uint8Array.
https://github.com/streamich/memfs/blob/05877386a95dab801621079ced2e09a45711e4d0/src/volume.ts#L1211-L1218
However, FsWriteStream.prototype._write only allows a type of Buffer:
https://github.com/streamich/memfs/blob/05877386a95dab801621079ced2e09a45711e4d0/src/volume.ts#L2569-L2591
This issue does cause an error of the combination: webpack 5 + node-downloader-helper + memfs.
node-downloader-helper and its dependencies can call FsWriteStream.prototype._write with a data of type Uint8Array.
(If anyone has an interest for an example, please try my project https://github.com/MrMYHuang/taa with memfs 3.4.3.)
After applying my changes, this issues is fixed.
=> fix: allow `Uint8Array`s to be passed to `FsWriteStream`

package.json, renovate.json, yarn.lock
This relaxes our one dependency constraint to allow minor and patch versions, and switches renovate to just do a lockfile refresh once a month.
This should greatly cut back on the noise without any downside since we don't need to have our dependencies pinned or updated that frequently given they're all dev dependencies, and our one non-dev dependency is our own anyway.
=> fix: loosen dependency constraints

src/__tests__/process.test.ts
This is now redundant because it's not actually testing anything useful - either the methods will be defined, which in case we're testing node internals, or they won't and we're testing the JS engines ability to implement syntax.
=> test: remove redundant case

src/__tests__/volume.test.ts, src/volume.ts
- "EISDIR: illegal operation on a directory, open ..." error
- https://github.com/streamich/memfs/issues/391
Resolves #391
=> fix: support calling `utimes` on a directory

src/__tests__/volume.test.ts, src/volume.ts
https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fsmkdirpath-options-callback
> The callback is given a possible exception and, if recursive is true, the first directory path created, (err[, path]). path can still be undefined when recursive is true, if no directory was created.
https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fsmkdirsyncpath-options
> Synchronously creates a directory. Returns undefined, or if recursive is true, the first directory path created.
Resolves #546
=> fix: `mkdir` return value

src/volume.ts
Signed-off-by: Sebastian Malton <sebastian@malton.name>
=> fix: set `path` on errors when possible

src/__tests__/volume.test.ts, src/volume.ts
The `fs.watch` API has `recursive` option but it did not implement it. For example, the watching listener below will not be triggered:
```js
const vol = new Volume();
vol.mkdirSync('/test');
vol.watch('/', { recursive: true }, (eventType, filename) => {
// won't be triggered
console.log('fs.watch', eventType, filename);
});
setTimeout(() => {
vol.writeFileSync('/test/lol.txt', '2');
}, 1000);
```
---
Besides when a child file's content (not recursive) is changed, the listener will not be triggered too:
```js
const vol = new Volume();
vol.mkdirSync('/test');
vol.writeFileSync('/test/lol.txt', 'foo')
vol.watch('/test', { recursive: false }, (eventType, filename) => {
// won't be triggered
console.log('fs.watch', eventType, filename);
});
setTimeout(() => {
vol.writeFileSync('/test/lol.txt', …
```
=> feat(volume): support the recursive option for fs.watch()

src/__tests__/volume.test.ts, src/volume.ts
This addresses "enough" of the errors described [here](https://github.com/streamich/memfs/pull/902#issuecomment-1574385481), and which are currently causing the test suite for `unionfs` to fail when using the latest version of `memfs`.
I say "enough" because my testing indicates that the current implementation is still not 1:1 with native `fs`, and I wouldn't be surprised if this change doesn't work in all cases, but it does make is closer to native `fs` 🤷
=> fix: correctly output filename when watching files

package.json, yarn.lock
Version 1.0.4 supports `.rm` and `.rmSync`: https://github.com/streamich/fs-monkey/releases/tag/v1.0.4
Technically, the existing version specification allows this drift: https://github.com/streamich/memfs/blob/09eab278ec0deb82dd4576dea27a48930e4c0e9b/package.json#L78-L80
However, for completeness, we should use `^1.0.4` so `rm*` "just works".
Closes #884
=> fix: bump fs-monkey minimum version for rm support

package.json
It looks like prereleases are being done using non-prerelease versions i.e. 4.0, 4.1 - this might mean those versions are effectively burned, though I swear npm allowed you to unpublish or override a version if it was marked as a pre-release but I can't find that in the docs.
Still, this configuration should fix that so going forward changes to `next` should result in `4.2.0-rc1` etc.
The best way to apply this would be to merge it into `master` and then rebase `next` on to `master` to avoid a conflict - @streamich this should be done before any more changes are landed into `next` to avoid publishing more versions.
=> ci: properly release prereleases

README.md, demo/git/index.ts, demo/print/fs.ts, demo/volume/print-tree.ts, docs/node/reference.md, docs/print/index.md, src/__tests__/volume/readFile.test.ts, src/__tests__/volume/writeSync.test.ts, src/crud-to-cas/__tests__/CrudCas.test.ts, src/crud/__tests__/matryoshka.test.ts, src/fsa-to-crud/__tests__/FsaCrud.test.ts, src/fsa-to-node/__tests__/FsaNodeFs.test.ts, src/index.ts, src/node-to-crud/__tests__/FsaCrud.test.ts, src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts, src/node-to-fsa/__tests__/NodeFileSystemFileHandle.test.ts, src/node-to-fsa/__tests__/NodeFileSystemHandle.test.ts, src/node-to-fsa/__tests__/NodeFileSystemSyncAccessHandle.test.ts, src/node-to-fsa/__tests__/NodeFileSystemWritableFileStream.test.ts, src/node-to-fsa/__tests__/scenarios.test.ts, src/print/__tests__/index.test.ts, src/print/index.ts, src/volume.ts
Adds ability to print a folder as a text tree:
```ts
import { memfs } from 'memfs';
const { vol } = memfs({
'/Users/streamich/src/github/memfs/src': {
'package.json': '...',
'tsconfig.json': '...',
'index.ts': '...',
'util': {
'index.ts': '...',
'print': {
'index.ts': '...',
'printTree.ts': '...',
},
},
},
});
console.log(vol.toTree());
// Output:
// /
// └─ Users/
//    └─ streamich/
//       └─ src/
//          └─ github/
//             └─ memfs/
//                └─ src/
//                   ├─ index.ts
//                   ├─ package.json
//                   ├─ tsconfig.json
//                   └─ util/
//                      ├─ index.ts
//                      └─ print/
//                         ├─ index.ts
//                         └─ printTree.ts
```
=> Print tree

src/__tests__/volume/mkdirSync.test.ts, src/node.ts, src/volume.ts
The PR closes #938.
`Link` is currently using a plain object (`Record<string, Link>`) to hold the `children` information. The PR repalces the plain object with `Map`.
=> fix: support directories named `__proto__`

src/Stats.ts, src/__tests__/volume.test.ts
Hello, I use memfs for writing unit tests for file system-related Node.js code. I recently noticed that the current implementation of `Stats` lacks nanosecond-precision properties (`atimeNs`, etc.) compared to Node.js one.
This PR adds those properties for better compatibility.
fixes #775 (not sure why it has been closed though)
=> fix: add missing nanosecond-precision properties to Stats

src/__tests__/volume.test.ts, src/volume.ts
> *I had to recreate the PR since I fumbled a bit and force-pushed at some point*
Review feedback from the #880.
Note that this PR is isolated and does not include #880 
Extended `vol.toJSON` so it can now output the virtual directory structure as a map of `Buffer` if the `asBuffer` parameter is set to `true`
=> feat(volume): `toJSON` now accepts the `asBuffer` parameter 

docs/node/reference.md, src/__tests__/volume.test.ts, src/volume.ts
Hi ! While trying to inject some `Buffer` into a `memfs` volume from the `fromJSON` method, I noticed it creates a virtual folder. I expected the method to accept `Buffer` as content but I noticed only `string` are "allowed".
This PR resolves cases when you want to inject raw binary data into your volumes. For example when you have some test archives to validate.
I have written a small patch to fix the issue. I tried to make as few changes as possible. It comes with a new test and some adjustments to the documentation.
I hope it's enough for a quick merge. If not, feel free to share adjustments you would like to be done. I'll try to be as reactive as possible.
Best regards,
Stanley.
=> feat(volume): now handling `Buffer` as volume content

docs/fsa/fsa-to-fs.md
Remove a double _web_ in [_File System Access API to Node fs API_](https://github.com/streamich/memfs/blob/edea9dd/docs/fsa/fsa-to-fs.md#file-system-access-api-to-node-fs-api) page:
> _This adapter implements Node's fs-like filesystem API on top of the **web web** [File System Access (FSA) API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)._
=> docs: remove a double 'web'

docs/node/usage.md
Fix link to `unionfs` in [_Usage_](https://github.com/streamich/memfs/blob/252a507/docs/node/usage.md#usage) page.
=> docs: fix link to unionfs

src/fsa-to-node/__tests__/FsaNodeFs.test.ts
This is returning a slightly different order on Windows - as far as I know the order is not guaranteed since we're testing using `includes` in all other tests but this one.
=> test: do not rely on element order

src/Dirent.ts, src/__tests__/volume/readdirSync.test.ts, src/node/options.ts, src/node/types/options.ts, src/volume.ts
Fix readdir recursive option and path to Dirent when withFileTypes: true
There wasn't a good way to do {recursive: true, withFileTypes: false} without making too many code paths.
I refactored it to calculate the data needed for { withFileTypes: true }, made a code path for function recursion if ( recursive: true }, and then original call returns just the paths if it's options were {withFileTypes: false} 
There may be a better way to do it, but that's what I got from my first look in the code.
Resolves #967
=> feat: add support for `recursive` to `readdir`

src/volume.ts
=> fix: ensure consistent file path formatting when reading directories recursively

src/fsa-to-node/FsaNodeFs.ts, src/node-to-fsa/NodeFileSystemSyncAccessHandle.ts, src/node-to-fsa/NodeFileSystemWritableFileStream.ts, src/node.ts, src/node/util.ts, src/webfs/index.ts
This prevents the need to shim Buffer on window in a browser based project, which reduces complexity in the build chain for such projects.
=> fix: use internal buffer instead of global Buffer

package.json
This is arguably breaking but `json-joy` is 30mb on disk and not required for the core fs system which I think is what most people are using so I'm willing to risk it in a minor version
Going to land it in a pre-release first to test - alternatively we could just inline the functions we're using from these dependencies.
=> feat: make `json-joy` and `thingies` dependencies optional

package.json, yarn.lock
This doesn't need to be a peer dependency since its used directly and its safe for multiple versions to exist on the tree
=> fix: make `tslib` a direct dependency

package.json, src/json-joy/util/buffers/utf8/CachedUtf8Decoder.ts, src/json-joy/util/buffers/utf8/randomU32.ts, yarn.lock
I didn't realise how small our dependency on this was, so its totally worth inlining
=> fix: inline `hyperdyperid`

package.json
I thought these were already being excluded but they're not which explains why the package is still so big
=> fix: remove tests from published package

src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts, src/node-to-fsa/util.ts
Hi,
I was using node-to-fsa and realized that files beginning with a period, as in hidden *nix files, throw 
```typescript
new TypeError(`Failed to execute '${method}' on '${klass}': Name is not allowed.`);
```
from `src/node-to-fsa/util.ts:assertName`.
I am assuming that this is not an intended behavior, if this is a correct assumption, please accept my pull request.
I modified the regex and added a regression test case.
=> fix: fix name validation regex to accept file names beginning with a period

src/node-to-fsa/NodeFileSystemDirectoryHandle.ts, src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
Hi! Thanks for working on this library. The File System Access API adapter has been helpful for testing a project I'm working on.
I noticed in one of my test suites that when using file handles retrieved from the `NodeFileSystemDirectoryHandle.entries()` async iterator, the `getFile()` method would throw an ENOENT error, with the message suggesting it was trying to read the file using just the name instead of the full path.
This appears to be a typo in the implementation, so I changed it to pass the full path when constructing file handles and added an assertion to the relevant test case that checks that the file entries can be read.
=> fix: fix handle paths in FSA entries iterator

src/Dirent.ts, src/__tests__/volume/readdirSync.test.ts, src/node.ts, src/volume.ts
This solves issue #1007 and is in large part the solution of @zzzzBuv though with some tests changed for conformance with node and readdir recursive fix.
src/dirent.path is only the path of the parent dir and dirent.name is either the filename+extension or the directory name. This is now reflected in readdir. Because readdir constructs the filenames from the readdir we join(path,name).
I had to change the test with readdir({withFileType: true}) because they were out of spec with node.
To test for conformance i used a simple script (node version v21.7.2)
```js
const fs = require('fs');
const path = require('path');
async function Test() {
const dir = path.join(process.cwd());
console.log('readdirSync(withFileTypes, recursive)');
let res = fs.readdirSync(dir, { withFileTypes: true, …
```
=> fix: don't include filename in `path` when calling `readdir` with `withFileTypes: true`

src/__tests__/volume.test.ts, src/volume.ts
Without that, `asBuffer` only works for files at the root of the volume, not those in sub-directories.
=> fix: ensure files in subdirectories are returned as buffers when calling `toJSON` with `asBuffer`

src/node/types/misc.ts
=> fix: 🐛 declare ReadableStream global type

src/Dirent.ts, src/__tests__/volume/readdirSync.test.ts, src/volume.ts
- Add missing `parentPath` property to `Dirent` which is equal to the `path` property
The `parentPath` property will replace the `path` property on `Dirent` in future node versions (see [Docs](https://nodejs.org/api/fs.html#class-fsdirent)).
References #735
=> fix: add `parentPath` to `Dirent`

src/__tests__/volume/lutimesSync.test.ts, src/node/lists/fsCallbackApiList.ts, src/node/lists/fsSynchronousApiList.ts, src/volume.ts
Let's try this again...
Continuation of https://github.com/streamich/memfs/pull/1065
=> feat: implement lutimes

src/__tests__/promises.test.ts, src/node/FsPromises.ts, src/node/types/FsPromisesApi.ts, src/node/types/misc.ts, src/node/util.ts
Now supporting streams as `writeFile()` data source in the Promises API, which makes it more compliant to the [Node.js Promises API](https://nodejs.org/docs/latest-v20.x/api/fs.html#fspromiseswritefilefile-data-options).
What's still missing is the support for `AsyncIterable` and `Iterable`. I can implement them as well if this PR gets approved.
Closes #1068
=> feat: support stream as source in promises version of `writeFile`

src/__tests__/volume.test.ts, src/volume.ts
Letting this option be a `FileHandle` aligns the API with [Node.js's `fs` module](https://nodejs.org/api/fs.html#fscreatewritestreampath-options).
(Split out from #1076 per request)
=> fix: accept passing a `FileHandle` to `createReadStream` and `createWriteStream`

src/__tests__/promises.test.ts, src/node/FileHandle.ts, src/node/types/misc.ts, src/node/types/options.ts
Closes #1063
Thanks for making this library! My test needed these methods to exist so I took a stab at adding support.
=> feat: implement `createReadStream` and `createWriteStream` on `FileHandle`

src/__tests__/volume.test.ts, src/node.ts, src/volume.ts
Fixes #725.
Symlinks are intended to be stored as relative paths to their target file.
=> fix: resolve relative symlinks to the current directory

src/__tests__/volume.test.ts, src/volume.ts
Spent a day tracking this down so I figured I could put in a fix. To review, the issue is that if you have a stream that happens to be open when you call `reset`, you get an error like this (assuming jest, but I'm sure it comes as a surprise to anyone on any testing platform):
```
> npx jest
Error: Unhandled error. (Error: EBADF: bad file descriptor, close
at createError (/path/to/project/node_modules/memfs/src/node/util.ts:146:17)
at Volume.getFileByFdOrThrow (/path/to/project/node_modules/memfs/src/volume.ts:540:33)
at Volume.closeSync (/path/to/project/node_modules/memfs/src/volume.ts:818:23)
at Immediate._onImmediate (/path/to/project/node_modules/memfs/src/volume.ts:578:25)
at processImmediate (node:internal/timers:478:21)
at process.topLevelDomainCallback (node:domain:160:15)
at …
```
=> fix: don't fail on closing fd after reset has been called (#550)

src/__tests__/volume.test.ts, src/__tests__/volume/__snapshots__/renameSync.test.ts.snap, src/node/constants.ts, src/node/types/misc.ts, src/node/util.ts, src/volume.ts
This seems reasonable, considering memfs supports the browser, and users are more likely to have instances of Uint8Array there.
Resolves https://github.com/streamich/memfs/issues/733
=> feat: support `UInt8Array` in place of `Buffer`

src/index.ts
This is a little fix that allows the code to work better with TS.
Currently `Volume` is re-exported as a `const` that aliases the class declaration.
This makes it very hard to use the class -- for example the following idiomatic TS code is now invalid:
```ts
import { Volume } from 'memfs';
function foo(volume: Volume) { }
//                   ^^^^^^ 'Volume' refers to a value, but is being used as a type here. Did you mean 'typeof Volume'?
// NOTE: the suggestion in the error is wrong and will not allow you to assign an instance
function bar(volume: typeof Volume) { }
bar(new Volume());
//  ^^^^^^^^^^^^ Argument of type 'Volume' is not assignable to parameter of type 'typeof Volume'.
//    Type 'Volume' is missing the following properties from type 'typeof Volume': prototype, fd
```
If we …
=> fix: export `Volume` class directly rather than as a `const`

src/node/util.ts
I slightly simplified the `genRndStr6` function by using `padEnd` for cases where the string is shorter than 6 characters. In most cases, padEnd isn’t applied, and the strings are sufficiently unique—just like in the original version.
https://gist.github.com/Connormiha/c42e57ecd1f934dea49877f5d7f815cb
By the way, package.json specifies Node >=4, but I believe that's outdated, since the project already uses `includes`, `await`, and the spread operator.
=> refactor: simplified genRndStr6 without recursion

src/snapshot/async.ts
This set uses await inside a loop, which means the next iteration doesn't start until the current promise is resolved. Since this is building a dictionary, it can be done in parallel to avoid blocking the next promise.
=> perf: remove await in loop for toSnapshot
